name: Close invalid PRs
on:
  pull_request:
    types: [labeled]

jobs:
  delete-pr:
    runs-on: ubuntu-latest
    steps:
      - name: close invalid PRs
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/prabolabam/fsa-presentation/pulls/${{ github.event.pull_request.number }}
          state: 'closed'
