name: Close invalid PRs
on:
  pull_request:
    types: 
      - labeled

jobs:
  delete-pr:
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    steps:
      - name: Close invalid PRs
        run: |
          echo ${{ github.event }}
 #         gh pr close ${{ github.event.pull_request.number }} -d
